### ISSUE TITLE
how to change activity

### ISSUE THREAD

**Issue by pengengantibaju** [vsec7/DCBot-On24x7#1]
hello sir i wanna ask about how to change  assets={'large_image':'874485178242854993'}), and what i should use ?

**Comment by vsec7** [comment]
1. Create dummy Bot on discord developer portal
2. Settings -> Rich Presence 
3. Add image on rich presence assets
4. After image uploaded , inspect element / right click on small image .
5. Search string like this https://cdn.discordapp.com/app-assets/874469380765913109/874485178242854993.png 
Eg : my image id is 874485178242854993
